# Generated by Django 5.1 on 2024-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
